project_id = "nmibwtbrbpqfvseeflep"

[functions.send-discord-notification]
verify_jwt = false

[functions.generate-lease-pdf]
verify_jwt = false

[functions.create-payment-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.generate-lease-document]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.verify-payment-intent]
verify_jwt = false
